### PR TITLE
DTL

### PR DESCRIPTION
**Pull request by tanksha**
Refactored the experimental code into a module (for DTL version only) along with the tests.

I moved the query/source to be the last argument when calling the chainer.

### CODE REVIEW

**Comment by ngeiswei** [comment]
Thanks Hedra.  We'll need to harmonize the names (syn vs synthesize vs bc, etc) but we can do that progressively.

**Comment by tanksha** [comment]
Sure. I can remove the bc inside curried forward and let the user know that they need to import the curried backward chainer in order to use the forward chainer, I can modify the tests to reflect that as well.

**Comment by ngeiswei** [comment]
Can you have the forward chainer module automatically import the backward chainer module?

**Comment by tanksha** [comment]
I can do that, the problem is when it is then imported in some other file (e.g I am using it in Miner and I got Failed to resolve module error) because the interpreter is not able to resolve the path.

**Pull request merged**
